version: "3.8"
services:
  backend:
    restart: always
    command: yarn dev
    ports:
      - "3000:3000"
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  frontend:
    build: frontend
    command: yarn dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/app
    depends_on:
      - backend
  mongo:
    restart: always
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data:/data/db
    expose:
      - 27017
  #
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     -ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     -ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  #     -ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
networks:
  react-express:
  express-mongo:
